PR-32: Issue #76 TravisCI for LIKE
RGPosadas/SOEN341-UA2 pull request #84
Opened 2019-03-16 04:32 UTC by leuthotung

This PR references Issue #76 

Unit tests have been created for like

2019-03-19 19:22 UTC, RGPosadas requested changes

2019-03-19 19:22 UTC, RGPosadas commented on src/UserDatabase/test/test.js
> +               // process.exit();
Please delete this line as it is no longer needed

2019-03-19 19:29 UTC, RGPosadas approved these changes
Approved since Travis approves

2019-03-20 01:37 UTC, cindyslittleplanet approved these changes
All checks by Travis have been passed, so approved.

2019-03-20 01:40 UTC, merged